name       : perl-importer
version    : '0.026'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Importer-0.026.tar.gz : e08fa84e13cb998b7a897fc8ec9c3459fcc1716aff25cc343e36ef875891b0ef
homepage   : https://metacpan.org/pod/Importer
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Importer - Alternative but compatible interface to modules that export symbols.
description: |
    This module acts as a layer between Exporter and modules which consume exports. It is feature-compatible with Exporter, plus some much needed extras. You can use this to import symbols from any exporter that follows Exporters specification. The exporter modules themselves do not need to use or inherit from the Exporter module, they just need to set @EXPORT and/or other variables.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
